### ISSUE TITLE
Deprecated selector in `letter-spacing/styles/letter-spacing.less`

### ISSUE THREAD

**Issue by jeromelachaud** [SKAhack/letter-spacing#5]
In `letter-spacing/styles/letter-spacing.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .cursor` => `atom-text-editor.editor .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by skahack** [comment]
fixed cb0b69564f4ea920fd7bd5f50065f3ac7935d691
